### ISSUE TITLE
Not all pages have all data

### ISSUE THREAD

**Issue by rafihaque7** [rafihaque7/arcticsearch#3]
For example, Zillow group (ticker symbol: z) does not have all the data. 

To test the bug
If you call EmployeesLatest for Zillow, it will give you "Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 5, Size: 0"

You can test it out by running datatest.java, and just type in 'z'

**Comment by rafihaque7** [comment]
type z in the console

**Comment by yinghaoawang** [comment]
Now, properly catches exception and continues getting input
